[physical]
hbarc = 197.3269804
alpha_em = 0.0072973525693

[model]
label = "njl-standard"
version = "1.0"
N_color = 3
N_flavor = 3
rho0_fm3 = 0.16
Lambda_MeV = 602.3
G_over_Lambda2 = 1.835
K_over_Lambda5 = 12.36
m_ud0_MeV = 5.5
m_s0_MeV = 140.7
