"""Run one Issue #130 crossover-mu endpoint numerical pilot target.

The target list is generated by the solver-free preflight.  This runner only
evaluates the eight explicitly selected representative targets; it does not
modify the phase reference or infer a crossover point from oracle labels.
"""

using Pkg

const PROJECT_ROOT = normpath(joinpath(@__DIR__, "..", ".."))
Pkg.activate(PROJECT_ROOT)

using CSV
using Dates
using JSON3
using SHA

const HBARC_MEV_FM = 197.327
const SCHEMA_VERSION = "pnjl_issue130_crossover_mu_endpoint_pilot_v1"
const TARGET_SCHEMA = "pnjl_issue130_endpoint_refinement_preflight_v1"
const DEFAULT_POLICY = :rs_reduced_adaptive

if !isdefined(Main, :Models)
    include(joinpath(PROJECT_ROOT, "src", "models", "Models.jl"))
end
using Main.Models

_json_safe(::Nothing) = nothing
_json_safe(value::Bool) = value
_json_safe(value::Integer) = value
_json_safe(value::AbstractFloat) = isfinite(value) ? value : nothing
_json_safe(value::AbstractString) = String(value)
_json_safe(value::Symbol) = String(value)
_json_safe(value::NamedTuple) = Dict(string(name) => _json_safe(getproperty(value, name)) for name in keys(value))
_json_safe(value::AbstractDict) = Dict(string(key) => _json_safe(item) for (key, item) in value)
_json_safe(value::Tuple) = [_json_safe(item) for item in value]
_json_safe(value::AbstractArray) = [_json_safe(item) for item in value]
_json_safe(value) = string(value)

function _parse_cli(args)
    values = Dict{String, String}()
    index = 1
    while index <= length(args)
        argument = args[index]
        startswith(argument, "--") || throw(ArgumentError("unexpected argument: $(argument)"))
        token = argument[3:end]
        if occursin("=", token)
            key, value = split(token, "="; limit=2)
            values[key] = value
        else
            index == length(args) && throw(ArgumentError("missing value for --$(token)"))
            index += 1
            values[token] = args[index]
        end
        index += 1
    end
    return values
end

_required(values, key) = haskey(values, key) ? values[key] : throw(ArgumentError("missing --$(key)"))
_float(values, key, default) = haskey(values, key) ? parse(Float64, values[key]) : Float64(default)
_int(values, key, default) = haskey(values, key) ? parse(Int, values[key]) : Int(default)

function _git_commit(root)
    try
        return strip(readchomp(`git -C $root rev-parse HEAD`))
    catch
        return "unknown"
    end
end

function _target_row(path::String, target_id::String)
    isfile(path) || throw(ArgumentError("target list missing: $(path)"))
    rows = collect(CSV.File(path; silencewarnings=true))
    matches = [row for row in rows if String(row.target_id) == target_id]
    length(matches) == 1 || throw(ArgumentError("target_id=$(target_id) must resolve to exactly one row"))
    row = only(matches)
    String(row.target_kind) == "crossover_mu_endpoint" || throw(ArgumentError("target is not a crossover endpoint target"))
    String(row.physical_side) == "crossover_mu_lt_CEP_proxy" || throw(ArgumentError("target is not on the physical crossover side"))
    return row
end

function _target_float(row, field::Symbol)
    raw = getproperty(row, field)
    value = raw isa Real ? Float64(raw) : parse(Float64, String(raw))
    isfinite(value) || throw(ArgumentError("non-finite target field $(field)"))
    return value
end

function _probe_temperature(
        T_MeV::Float64,
        mu_MeV::Float64,
        xi::Float64;
        p_num::Int,
        t_num::Int,
        thermo_quadrature_policy::Symbol,
        thermo_quadrature_rtol::Float64,
        thermo_quadrature_atol::Float64,
        thermo_quadrature_maxevals::Int)
    T_fm = T_MeV / HBARC_MEV_FM
    mu_fm = mu_MeV / HBARC_MEV_FM
    try
        result = Models.solve_pnjl_with_derivatives(
            T_fm,
            mu_fm;
            order=1,
            xi=xi,
            p_num=p_num,
            t_num=t_num,
            thermo_quadrature_policy=thermo_quadrature_policy,
            thermo_quadrature_rtol=thermo_quadrature_rtol,
            thermo_quadrature_atol=thermo_quadrature_atol,
            thermo_quadrature_maxevals=thermo_quadrature_maxevals,
        )
        model = Models.create_model(:PNJL)
        mu_vec = Models.normalize_mu_vec(mu_fm)
        _, rho_norm, _, _ = Models.model_thermo(
            model,
            result.x,
            mu_vec,
            T_fm;
            xi=xi,
            p_num=p_num,
            t_num=t_num,
            thermo_quadrature_policy=thermo_quadrature_policy,
            thermo_quadrature_rtol=thermo_quadrature_rtol,
            thermo_quadrature_atol=thermo_quadrature_atol,
            thermo_quadrature_maxevals=thermo_quadrature_maxevals,
        )
        derivative = Float64(result.dx_dT[1])
        rho = Float64(rho_norm)
        finite = isfinite(derivative) && isfinite(rho) && all(isfinite, result.x)
        return (
            T_MeV=T_MeV,
            derivative=derivative,
            rho=rho,
            finite=finite,
            solver_ok=true,
            error="",
        )
    catch error_value
        return (
            T_MeV=T_MeV,
            derivative=NaN,
            rho=NaN,
            finite=false,
            solver_ok=false,
            error=sprint(showerror, error_value),
        )
    end
end

function _write_json(path::String, value)
    open(path, "w") do io
        JSON3.write(io, _json_safe(value))
        write(io, '\n')
    end
end

function _write_response_csv(path::String, rows)
    if isempty(rows)
        open(path, "w") do io
            write(io, "T_MeV,derivative,rho,finite,solver_ok,error,scan_derivative\n")
        end
    else
        CSV.write(path, rows)
    end
end

function _run(values)
    calculation_sha = _required(values, "calculation-sha")
    occursin(r"^[0-9a-fA-F]{40}$", calculation_sha) || throw(ArgumentError("calculation-sha must be a 40-character SHA"))
    target_id = _required(values, "target-id")
    target_list = abspath(_required(values, "target-list"))
    output_dir = abspath(_required(values, "output-dir"))
    tag = get(values, "tag", "issue130_crossover_mu_endpoint_pilot_v1")
    workflow_head_sha = get(values, "workflow-head-sha", "unknown")
    schema_version = get(values, "schema-version", SCHEMA_VERSION)
    target_selection = get(values, "target-selection", "pilot")
    target_selection in ("pilot", "full") || throw(ArgumentError("target-selection must be pilot or full"))

    row = _target_row(target_list, target_id)
    xi = _target_float(row, :xi)
    target_mu = _target_float(row, :target_mu_MeV)
    cep_proxy = _target_float(row, :mu_upper_bound_MeV)
    bracket_low = _target_float(row, :T_CEP_bracket_low_MeV)
    bracket_high = _target_float(row, :T_CEP_bracket_high_MeV)
    retained_T = _target_float(row, :last_retained_T_MeV)
    margin = _float(values, "temperature-margin", 0.5)
    T_min = max(1.0, bracket_low - margin)
    T_max = max(T_min + 0.25, max(bracket_high, retained_T) + margin)
    p_num = _int(values, "p-num", 24)
    t_num = _int(values, "t-num", 8)
    n_scan = _int(values, "n-scan", 20)
    max_iter = _int(values, "max-iter", 20)
    thermo_policy = Symbol(get(values, "thermo-quadrature-policy", String(DEFAULT_POLICY)))
    thermo_rtol = _float(values, "thermo-quadrature-rtol", 1e-8)
    thermo_atol = _float(values, "thermo-quadrature-atol", 1e-10)
    thermo_maxevals = _int(values, "thermo-quadrature-maxevals", 10^7)

    target_mu < cep_proxy || throw(ArgumentError("target mu is not strictly below CEP proxy"))
    started = time_ns()
    result = Models.detect_crossover(
        target_mu / HBARC_MEV_FM,
        (T_min / HBARC_MEV_FM, T_max / HBARC_MEV_FM);
        method=:peak,
        variable=:phi_u,
        xi=xi,
        n_scan=n_scan,
        tol=1e-4,
        max_iter=max_iter,
        p_num=p_num,
        t_num=t_num,
        thermo_quadrature_policy=thermo_policy,
        thermo_quadrature_rtol=thermo_rtol,
        thermo_quadrature_atol=thermo_atol,
        thermo_quadrature_maxevals=thermo_maxevals,
    )
    runner_seconds = (time_ns() - started) / 1e9

    scan_data = get(result.details, :scan_data, Tuple[])
    response_rows = NamedTuple[]
    for item in scan_data
        T_MeV = Float64(item[1]) * HBARC_MEV_FM
        derivative = Float64(item[2])
        probe = _probe_temperature(
            T_MeV,
            target_mu,
            xi;
            p_num=p_num,
            t_num=t_num,
            thermo_quadrature_policy=thermo_policy,
            thermo_quadrature_rtol=thermo_rtol,
            thermo_quadrature_atol=thermo_atol,
            thermo_quadrature_maxevals=thermo_maxevals,
        )
        push!(response_rows, merge(probe, (scan_derivative=derivative,)))
    end

    found = Bool(result.found)
    T_crossover = result.T_crossover === nothing ? NaN : Float64(result.T_crossover) * HBARC_MEV_FM
    rho_crossover = result.rho === nothing ? NaN : Float64(result.rho)
    derivative_peak = result.derivative_value === nothing ? NaN : Float64(result.derivative_value)
    supplemental_finite = all(row -> row.finite, response_rows)
    output = Dict(
        "schema_version" => schema_version,
        "target_schema" => TARGET_SCHEMA,
        "target_selection" => target_selection,
        "tag" => tag,
        "target_id" => target_id,
        "calculation_sha" => lowercase(calculation_sha),
        "workflow_head_sha" => workflow_head_sha,
        "runner_git_commit" => _git_commit(PROJECT_ROOT),
        "target_list" => relpath(target_list, PROJECT_ROOT),
        "target_list_sha256" => bytes2hex(sha256(read(target_list))),
        "target" => Dict(
            "xi" => xi,
            "target_mu_MeV" => target_mu,
            "mu_CEP_proxy_MeV" => cep_proxy,
            "T_CEP_bracket_low_MeV" => bracket_low,
            "T_CEP_bracket_high_MeV" => bracket_high,
            "last_retained_T_MeV" => retained_T,
            "physical_side" => "crossover_mu_lt_CEP_proxy",
        ),
        "temperature_window_MeV" => Dict("min" => T_min, "max" => T_max, "margin" => margin),
        "config" => Dict(
            "p_num" => p_num,
            "t_num" => t_num,
            "n_scan" => n_scan,
            "max_iter" => max_iter,
            "thermo_quadrature_policy" => String(thermo_policy),
            "thermo_quadrature_rtol" => thermo_rtol,
            "thermo_quadrature_atol" => thermo_atol,
            "thermo_quadrature_maxevals" => thermo_maxevals,
        ),
        "result" => Dict(
            "found" => found,
            "status" => found ? "crossover_candidate" : "not_found",
            "T_crossover_MeV" => T_crossover,
            "rho_crossover" => rho_crossover,
            "derivative_peak" => derivative_peak,
            "iterations" => Int(result.iterations),
            "details" => result.details,
        ),
        "finite_and_converged" => Bool(found && supplemental_finite),
        "supplemental_probe_count" => length(response_rows),
        "supplemental_probe_finite" => supplemental_finite,
        "solver" => Dict(
            "solver_called" => true,
            "solver_api" => "Models.detect_crossover + Models.solve_pnjl_with_derivatives",
            "telemetry_status" => "api_call_proxy_only",
            "telemetry_note" => "The public crossover API does not expose per-call SolverWorkTelemetry; scan and supplemental probe counts are recorded without inventing solver-attempt counters.",
            "estimated_detector_calls" => n_scan + 2 * Int(result.iterations) + (found ? 1 : 0),
        ),
        "runner_seconds" => runner_seconds,
    )

    mkpath(output_dir)
    _write_response_csv(joinpath(output_dir, "temperature_response.csv"), response_rows)
    _write_json(joinpath(output_dir, "target_summary.json"), output)
    _write_json(joinpath(output_dir, "provenance.json"), Dict(
        "schema_version" => schema_version,
        "target_selection" => target_selection,
        "calculation_sha" => lowercase(calculation_sha),
        "workflow_head_sha" => workflow_head_sha,
        "runner_git_commit" => _git_commit(PROJECT_ROOT),
        "solver_called" => true,
        "reference_write" => false,
        "target_id" => target_id,
        "target_list_sha256" => bytes2hex(sha256(read(target_list))),
        "generated_at" => Dates.format(Dates.now(Dates.UTC), dateformat"yyyy-mm-ddTHH:MM:SSZ"),
    ))
    println(JSON3.write(_json_safe(output)))
end

if abspath(PROGRAM_FILE) == @__FILE__
    _run(_parse_cli(ARGS))
end
