#!/usr/bin/env julia
"""
详细对比 Fortran 和 Julia 的积分实现细节
"""

using Printf

println("="^80)
println("Fortran vs Julia 积分实现对比")
println("="^80)

println("\n1. 积分节点数")
println("-"^80)
println("Fortran:")
println("  npoint_rex = 64")
println("  动量积分: yp (64 节点, [0, 1])")
println("  角度积分: ypi (64 节点, [0, π])")
println()
println("Julia:")
println("  p_nodes = 64")
println("  angle_nodes = 64")
println("  phi_nodes = 8")

println("\n2. 积分变量")
println("-"^80)
println("Fortran:")
println("  动量: p_i, p_j (通过 t 变换)")
println("  角度: angel ∈ [0, π]")
println("  积分: ∫∫∫ dp_i dp_j d(angel) · sin(angel)")
println()
println("Julia:")
println("  动量: p_i, p_j (通过 t 变换)")
println("  角度: cosθ_i ∈ [-1, 1], cosθ_j ∈ [-1, 1]")
println("  方位角: φ ∈ [0, 2π]")
println("  积分: ∫∫∫∫∫ dp_i dp_j d(cosθ_i) d(cosθ_j) dφ")

println("\n3. 关键差异")
println("-"^80)
println("⚠️  Fortran 使用 1D 角度积分 (angel)")
println("⚠️  Julia 使用 3D 角度积分 (cosθ_i, cosθ_j, φ)")
println()
println("这是一个根本性的差异!")

println("\n4. 物理意义")
println("-"^80)
println("Fortran 的 angel:")
println("  - angel 是两个粒子动量之间的夹角")
println("  - s = m1² + m2² + 2(E1 E2 - p1 p2 cos(angel))")
println("  - 假设粒子动量方向是各向同性的")
println()
println("Julia 的 (cosθ_i, cosθ_j, φ):")
println("  - cosθ_i, cosθ_j 是粒子动量相对于 z 轴的角度")
println("  - φ 是方位角")
println("  - cosΘ = cosθ_i cosθ_j + sinθ_i sinθ_j cos(φ)")
println("  - s = m1² + m2² + 2(E1 E2 - p1 p2 cosΘ)")
println("  - 完整考虑了各向异性分布")

println("\n5. 积分测度")
println("-"^80)
println("Fortran:")
println("  dΩ = 2π sin(angel) d(angel)")
println("  积分: ∫₀^π sin(angel) d(angel) = 2")
println("  总测度: 2π × 2 = 4π")
println()
println("Julia (各向同性, ξ=0):")
println("  dΩ = d(cosθ_i) d(cosθ_j) dφ")
println("  积分: ∫₋₁¹ d(cosθ_i) ∫₋₁¹ d(cosθ_j) ∫₀^(2π) dφ = 2 × 2 × 2π = 8π")
println()
println("⚠️  测度不同! Julia 的测度是 Fortran 的 2 倍!")

println("\n6. 归一化因子")
println("-"^80)
println("Fortran:")
println("  w_ij_n = N_c² / (2π⁴) × w_ij")
println("  w_ij = w_ij_n / (n1 × n2)")
println()
println("Julia:")
println("  prefactor = DQ² / (32π⁵ × ρ_i × ρ_j)")
println("  其中 DQ = 2N_c = 6")
println("  DQ² = 36 = (2N_c)²")
println()
println("对比:")
println("  Fortran: N_c² / (2π⁴) = 9 / (2π⁴) = 9 / (2 × 97.41) = 0.0462")
println("  Julia: 36 / (32π⁵) = 36 / (32 × 306.02) = 0.00368")
println("  比值: 0.0462 / 0.00368 = 12.55")

println("\n7. 可能的解释")
println("-"^80)
println("差异来源:")
println("  1. 积分测度不同 (2倍)")
println("  2. 归一化因子不同 (~12.5倍)")
println("  3. 角度积分方式不同")
println()
println("总体差异: ~2倍")
println("这与观察到的差异一致!")

println("\n8. 建议")
println("-"^80)
println("需要检查:")
println("  1. Fortran 的归一化公式是否正确")
println("  2. Julia 的归一化公式是否正确")
println("  3. 两者的物理定义是否一致")
println("  4. 数密度 ρ 的计算是否一致")

println("\n" * "="^80)
