#!/usr/bin/env julia

"""
Generate lightweight Claude Code skill wrappers from canonical `.agents/skills`.

The canonical SKILL.md remains the single source of workflow content. Claude wrappers
contain only trigger metadata, optional Claude-specific invocation controls, and a link
to the canonical file.

Usage:
  julia --project=. scripts/dev/sync_claude_skills.jl
  julia --project=. scripts/dev/sync_claude_skills.jl --check
  julia --project=. scripts/dev/sync_claude_skills.jl --source-root PATH --target-root PATH
"""

const ROOT = normpath(joinpath(@__DIR__, "..", ".."))
const DEFAULT_SOURCE_ROOT = joinpath(ROOT, ".agents", "skills")
const DEFAULT_TARGET_ROOT = joinpath(ROOT, ".claude", "skills")
const GENERATED_MARKER = "<!-- GENERATED BY scripts/dev/sync_claude_skills.jl; DO NOT EDIT -->"
const ALLOWED_CLAUDE_KEYS = Set([
    "disable-model-invocation",
    "user-invocable",
    "allowed-tools",
    "context",
    "agent",
])

normalize_text(text::AbstractString) = replace(text, "\r\n" => "\n", "\r" => "\n")

function parse_args(args)
    source_root = DEFAULT_SOURCE_ROOT
    target_root = DEFAULT_TARGET_ROOT
    check_only = false
    i = 1
    while i <= length(args)
        arg = args[i]
        if arg == "--source-root"
            i == length(args) && error("--source-root requires a path")
            i += 1
            source_root = abspath(args[i])
        elseif startswith(arg, "--source-root=")
            source_root = abspath(split(arg, '='; limit=2)[2])
        elseif arg == "--target-root"
            i == length(args) && error("--target-root requires a path")
            i += 1
            target_root = abspath(args[i])
        elseif startswith(arg, "--target-root=")
            target_root = abspath(split(arg, '='; limit=2)[2])
        elseif arg == "--check"
            check_only = true
        elseif arg in ("-h", "--help")
            println("Usage: julia --project=. scripts/dev/sync_claude_skills.jl [--source-root PATH] [--target-root PATH] [--check]")
            return nothing
        else
            error("unknown option: $(arg)")
        end
        i += 1
    end
    return (; source_root=normpath(source_root), target_root=normpath(target_root), check_only)
end

function skill_files(root::String)
    files = Dict{String,String}()
    isdir(root) || return files
    for name in sort(readdir(root))
        skill_md = joinpath(root, name, "SKILL.md")
        isfile(skill_md) || continue
        files[name] = skill_md
    end
    return files
end

function unquote_yaml_scalar(value::AbstractString)
    length(value) >= 2 || return String(value)
    if (startswith(value, '"') && endswith(value, '"')) ||
       (startswith(value, '\'') && endswith(value, '\''))
        return String(value[2:end-1])
    end
    return String(value)
end

function read_frontmatter(skill_md::String)
    lines = split(normalize_text(read(skill_md, String)), '\n'; keepempty=true)
    !isempty(lines) && lines[1] == "---" || error("$(skill_md): missing frontmatter")
    closing = findnext(==("---"), lines, 2)
    closing === nothing && error("$(skill_md): missing frontmatter closing delimiter")

    fields = Dict{String,String}()
    for line in lines[2:closing-1]
        (!isempty(line) && isspace(first(line))) && continue
        m = match(r"^([A-Za-z0-9_-]+):\s*(.*)$", line)
        m === nothing && continue
        fields[m.captures[1]] = unquote_yaml_scalar(strip(m.captures[2]))
    end
    name = get(fields, "name", "")
    description = get(fields, "description", "")
    isempty(name) && error("$(skill_md): missing name")
    isempty(description) && error("$(skill_md): missing description")
    return name, description
end

function yaml_quote(value::AbstractString)
    escaped = replace(value, '\\' => "\\\\", '"' => "\\\"", '\n' => "\\n")
    return "\"$(escaped)\""
end

function read_claude_options(skill_dir::String)
    path = joinpath(skill_dir, "agents", "claude.yaml")
    isfile(path) || return Pair{String,String}[]
    options = Pair{String,String}[]
    for (line_number, line) in enumerate(eachline(path))
        stripped = strip(line)
        isempty(stripped) && continue
        startswith(stripped, '#') && continue
        m = match(r"^([A-Za-z0-9_-]+):\s*(.+)$", stripped)
        m === nothing && error("$(path):$(line_number): expected key: value")
        key = m.captures[1]
        key in ALLOWED_CLAUDE_KEYS || error("$(path):$(line_number): unsupported Claude key $(key)")
        push!(options, key => strip(m.captures[2]))
    end
    return options
end

function wrapper_content(skill_name::String, description::String, canonical_path::String, wrapper_dir::String, options)
    relative = replace(relpath(canonical_path, wrapper_dir), '\\' => '/')
    lines = String[
        "---",
        "name: $(skill_name)",
        "description: $(yaml_quote(description))",
    ]
    for (key, value) in options
        push!(lines, "$(key): $(value)")
    end
    append!(lines, [
        "---",
        "",
        GENERATED_MARKER,
        "",
        "Read and follow the canonical skill instructions in [canonical SKILL.md]($(relative)).",
        "",
        "Use the current user request and task context unchanged. Do not duplicate or reinterpret the canonical workflow in this wrapper.",
        "",
    ])
    return join(lines, "\n")
end

function assert_target_child(path::String, target_root::String)
    full = normpath(abspath(path))
    relative = relpath(full, target_root)
    (relative == "." || startswith(relative, "..")) && error("path escapes target root: $(full)")
    return full
end

function existing_generated_wrappers(target_root::String)
    wrappers = Dict{String,String}()
    isdir(target_root) || return wrappers
    for name in readdir(target_root)
        wrapper = joinpath(target_root, name, "SKILL.md")
        isfile(wrapper) || continue
        occursin(GENERATED_MARKER, read(wrapper, String)) || continue
        wrappers[name] = wrapper
    end
    return wrappers
end

function main()
    parsed = parse_args(ARGS)
    parsed === nothing && return
    isdir(parsed.source_root) || error("source root does not exist: $(parsed.source_root)")

    source_skills = skill_files(parsed.source_root)
    isempty(source_skills) && error("no canonical skills found under $(parsed.source_root)")

    expected = Dict{String,String}()
    for name in sort(collect(keys(source_skills)))
        canonical = source_skills[name]
        declared_name, description = read_frontmatter(canonical)
        declared_name == name || error("$(canonical): name $(declared_name) does not match folder $(name)")
        wrapper_dir = joinpath(parsed.target_root, name)
        options = read_claude_options(dirname(canonical))
        expected[name] = wrapper_content(name, description, canonical, wrapper_dir, options)
    end

    existing_generated = existing_generated_wrappers(parsed.target_root)
    violations = String[]

    for name in sort(collect(keys(expected)))
        wrapper = joinpath(parsed.target_root, name, "SKILL.md")
        if parsed.check_only
            if !isfile(wrapper)
                push!(violations, "missing wrapper: $(wrapper)")
            elseif normalize_text(read(wrapper, String)) != normalize_text(expected[name])
                push!(violations, "stale wrapper: $(wrapper)")
            end
            continue
        end

        assert_target_child(wrapper, parsed.target_root)
        if isfile(wrapper) && !occursin(GENERATED_MARKER, read(wrapper, String))
            error("refusing to overwrite non-generated Claude skill: $(wrapper)")
        end
        mkpath(dirname(wrapper))
        write(wrapper, expected[name])
    end

    stale_names = sort(setdiff(collect(keys(existing_generated)), collect(keys(expected))))
    for name in stale_names
        wrapper_dir = assert_target_child(dirname(existing_generated[name]), parsed.target_root)
        if parsed.check_only
            push!(violations, "stale generated wrapper directory: $(wrapper_dir)")
        else
            rm(wrapper_dir; recursive=true)
        end
    end

    if !isempty(violations)
        println("[claude-skill-sync] FAILED: $(length(violations)) issue(s)")
        for item in violations
            println(" - " * item)
        end
        exit(1)
    end

    mode = parsed.check_only ? "CHECKED" : "SYNCED"
    println("[claude-skill-sync] $(mode)")
    println("  source=$(parsed.source_root)")
    println("  target=$(parsed.target_root)")
    println("  skills=$(length(expected))")
end

main()
