export AbstractQCDModel, AbstractNJLModel, AbstractPNJLModel
export UnsupportedCapabilityError, ModelCapabilities, model_capabilities, require_capability
export calculate_mass_vec, calculate_chiral
export vacuum_contribution, thermal_contribution, polyakov_potential
export number_densities
export NJLModel
export NJL2Model
export PNJLModel
export PNJLMagneticModel
export MagneticGapCandidate, MagneticGapResult
export magnetic_gap_residual, solve_magnetic_gap
export RPNJLModel
export RotationModel
export create_model
export get_cached_model, clear_model_cache!
export register_model!, unregister_model!, registered_model_kinds
export omega, omega_components, grand_potential
export model_pressure, model_rho, model_thermo
export MeanFieldState
export meanfield_state, state_vector
export normalize_mu_vec
export solve_gap
export gap_state_dim, gap_residual
export ImplicitProblem
export build_pnjl_fixedmu_problem, build_pnjl_flavor_mu_problem, build_njl_problem
export derive_vec, derive_named
export solve_pnjl_with_derivatives
export solve_pnjl_with_flavor_mu_derivatives
export mass_derivatives, thermo_derivatives, bulk_derivative_coeffs
export bulk_viscosity_coefficients, compute_B_bracket
export dP_dT, dP_dmu
export flavor_pressure_derivatives, conserved_charge_susceptibility
export chi_BQS, cumulant_BQS
export nth_derivative, susceptibility_scale
export AbstractChiProvider, chi_provider_name
export chi_B, chi1_B, chi2_B, chi3_B, chi4_B
export chi_Q, chi1_Q, chi2_Q, chi3_Q, chi4_Q
export chi_S, chi1_S, chi2_S, chi3_S, chi4_S
export chi11_BQ, chi11_BS, chi11_QS
export cumulant_B, baryon_Ssigma, baryon_kappa_sigma2
export default_hard_constraint_rules
export evaluate_hard_constraints
export select_pressure_max_candidate
export solve_constraint
export solve, solve_multi, SolverResult
export SOLVER_CONTRACT_VERSION_V1, SOLVER_RESULT_REQUIRED_FIELDS
export solver_contract_version, to_namedtuple
export coerce_solver_result, solver_result_view, solver_result_is_success
export solve_vec, solve_named
export ModelStateSchema, schema_for_model, flatten_state, unflatten_state
export ConstraintModes
export state_var_dim, mu_var_dim, solution_dim
export ProblemSpec, build_problem_spec, ExtraConstraints, default_extra_constraints
export AbstractConstraintComponent
export constraint_name, constraint_dim, build_constraint_components, constraint_total_dim
export HardRule, CandidateSelector, build_candidate_context
export evaluate_candidate_success, normalize_governance_candidate, build_seed_pool
export classify_attempt_error, normalize_error_message
export governance_quality_tag, normalize_selector_candidates, execute_governance_selector
export build_governance_candidate
export SolverDiagnosticSummary, SolverDiagnosticCandidate, SolverDiagnosticFull
export SOLVER_DIAGNOSTIC_VERSION_V1, SOLVER_DIAGNOSTIC_PUBLIC_FIELDS, SOLVER_DIAGNOSTIC_INTERNAL_FIELDS
export solver_diagnostic_version, solver_diagnostic_public_fields, solver_diagnostic_internal_fields
export to_public_namedtuple
export coerce_solver_diagnostic_summary, coerce_solver_diagnostic_public_view
export SolverWorkTelemetry, solver_work_snapshot, reset_solver_work!
export record_solver_request!, record_governed_attempt!, record_nlsolve_work!
export record_postprocess_residual!, record_attempt_outcome!, record_solver_exception!, record_scan_retry!
export VarSchema, SchemaRegistry, register_schema!, schema_for, validate_schema
export named_to_vec, vec_to_named
export state_view, mu_view
export PrimaryStrategy
export SeedStrategy, DefaultSeed, MultiSeed, HybridContinuitySeed
export get_seed, update!, get_all_seeds
export HADRON_SEED_5, QUARK_SEED_5, HADRON_SEED_8, QUARK_SEED_8
export build_conditions, build_residual!, gap_core_residual!, GapParams
export explicit_residual, explicit_residual!
export solve_weighted_block_fallback
export solve_with_derivatives
export is_physical_solution
export RootProblemSpec, RootPolicy, ContinuationState, RootAttempt, RootDiagnostics, RootSolveResult
export solve_root_with_policy, solve_root_continuation
export ρ0
export QUARK_CHARGE_ABS
export alpha_n, energy_landau, smooth_cutoff, resolve_nmax_from_cutoff
export omega0_flavor_landau, omegat_flavor_landau, density_flavor_landau
export MagneticIMCParams, default_imc_params, coupling_GB
export MagneticConfig, default_magnetic_config
export calculate_magnetic_omega_components, calculate_magnetic_omega
export calculate_magnetic_pressure, calculate_magnetic_rho
export calculate_magnetic_number_densities
export magnetic_nmax_convergence_report
export transport_provider
export TransportProvider
export prepare_transport_provider
export default_momentum_count, default_theta_count
export default_momentum_nodes, default_momentum_weights
export CEPResult, CEP_RESULT_STATUSES, FirstOrderSweepResult, RhoHybridVerificationConfig, ProductionPipelineConfig, PromotionResult, PhasePipelineResult
export RhoSupportConfig, RhoSupportPrior, RhoSupportAssessment, analyze_rho_support_cascade
export AbstractPipelineIOContract, PipelineIOContract
export PipelineProvenance, PipelineSpec, PipelineStage, PipelineContext, PipelineArtifact, StageResult
export persisted_symbol_to_string, persisted_string_to_symbol
export PipelineStageRecord, PipelineRunResult
export run_pipeline, compute_pipeline_config_hash, compute_pipeline_artifact_hash
export build_manifest_extensions
export normalize_adapter_kwargs, classify_pipeline_error
export adapter_repo_root, adapter_git_commit, adapter_config_hash, resolve_adapter_output_dir
export PHASE_PIPELINE_STAGE_IDS, run_phase_pipeline_via_runner
export workflow_pipeline_stage_ids, scan_pipeline_stage_ids, relaxtime_orchestrator_stage_ids
export PM_BRANCH_STATUSES, PM_SEED_SOURCES, PM_ENDPOINT_CAUSES, PM_COMPARISON_STATUSES
export PMSeedPair
export Integrals, cached_nodes, vacuum_integral, calculate_energy_sum, calculate_number_densities
export Constants_PNJL
export TmuScanConfig, TrhoScanConfig
export FreezeoutScanConfig
export FreezeoutParameterProfile
export load_freezeout_profile, freezeout_profile_dir
export freezeout_muB_GeV, freezeout_temperature_GeV
export freezeout_point_GeV, freezeout_point_MeV
export build_freezeout_scan_points
export MesonChemicalProfile
export meson_chemical_profile_dir, load_meson_chemical_profile
export meson_chemical_profile_MeV, meson_chemical_profile_fm
export run_precompile_workload
export run_precompile_profile, run_precompile_capability
export list_precompile_capabilities, list_precompile_profile
export ThermoDiffContext, DiffTarget, ParamSpec
export build_thermo_diff_context, diff_target, jacobian
export build_pilot_diff_context, eval_pilot_derivatives
export build_diff_service_context, eval_diff_service_jacobian
