#!/usr/bin/env python3

import argparse
import csv
import json
from pathlib import Path


def parse_args():
    parser = argparse.ArgumentParser(
        description="Validate dense reference artifacts generated by build_dense_phase_reference.jl"
    )
    parser.add_argument("--reference-root", required=True, help="Directory containing generated reference artifacts")
    parser.add_argument("--tag", required=True, help="Artifact tag suffix")
    parser.add_argument("--min-crossover-rows", type=int, default=1, help="Minimum expected data rows in crossover csv")
    parser.add_argument("--expect-crossover-only", action="store_true", help="Assert that only crossover artifacts are present")
    parser.add_argument("--expect-mu0-only", action="store_true", help="Assert that all mu_MeV values are zero")
    parser.add_argument("--report-path", help="Optional JSON report output path")
    return parser.parse_args()


def fail(message: str):
    raise SystemExit(f"[dense-reference-validate] {message}")


def load_json(path: Path):
    with path.open("r", encoding="utf-8") as fh:
        return json.load(fh)


def load_csv_rows(path: Path):
    with path.open("r", encoding="utf-8", newline="") as fh:
        reader = csv.DictReader(fh)
        rows = list(reader)
    return reader.fieldnames or [], rows


def normalize_relpath(path: Path, root: Path) -> str:
    try:
        return path.relative_to(root).as_posix()
    except ValueError:
        return path.as_posix()


def main():
    args = parse_args()
    repo_root = Path(__file__).resolve().parents[2]
    reference_root = Path(args.reference_root).resolve()

    crossover_csv = reference_root / f"crossover_{args.tag}.csv"
    crossover_meta = reference_root / f"crossover_{args.tag}.meta.json"
    manifest_path = reference_root / f"phase_reference_{args.tag}_manifest.json"

    required_paths = [crossover_csv, crossover_meta, manifest_path]
    for path in required_paths:
        if not path.is_file():
            fail(f"missing required artifact: {path}")

    fieldnames, rows = load_csv_rows(crossover_csv)
    if len(rows) < args.min_crossover_rows:
        fail(f"crossover row count {len(rows)} < required minimum {args.min_crossover_rows}")

    expected_columns = [
        "xi",
        "mu_MeV",
        "T_crossover_MeV",
        "rho",
        "method",
        "converged",
        "derivative",
        "variable",
    ]
    if fieldnames != expected_columns:
        fail(f"unexpected crossover columns: {fieldnames}")

    meta = load_json(crossover_meta)
    manifest = load_json(manifest_path)

    artifact_info = meta.get("artifact", {})
    if artifact_info.get("row_count") != len(rows):
        fail("meta artifact.row_count does not match crossover csv row count")

    meta_relpath = artifact_info.get("path")
    expected_meta_relpath = normalize_relpath(crossover_csv, repo_root)
    if meta_relpath != expected_meta_relpath:
        fail(f"meta artifact.path mismatch: expected {expected_meta_relpath}, got {meta_relpath}")

    manifest_generator = manifest.get("generator", {})
    meta_generator = meta.get("generator", {})
    if manifest_generator.get("git_commit") != meta_generator.get("git_commit"):
        fail("manifest generator.git_commit does not match meta generator.git_commit")

    if manifest_generator.get("crossover_only") != args.expect_crossover_only:
        fail("manifest crossover_only flag does not match workflow expectation")
    if manifest_generator.get("crossover_mu0_only") != args.expect_mu0_only:
        fail("manifest crossover_mu0_only flag does not match workflow expectation")

    artifacts = manifest.get("artifacts", {})
    crossover_artifact = artifacts.get("crossover", {})
    if crossover_artifact.get("row_count") != len(rows):
        fail("manifest artifacts.crossover.row_count does not match crossover csv row count")
    expected_manifest_relpath = normalize_relpath(crossover_csv, repo_root)
    if crossover_artifact.get("path") != expected_manifest_relpath:
        fail("manifest artifacts.crossover.path does not match crossover csv path")

    if args.expect_crossover_only:
        unexpected = [name for name in ("boundary", "cep", "spinodals") if name in artifacts]
        if unexpected:
            fail(f"unexpected non-crossover artifacts present: {unexpected}")

    xi_values = sorted({float(row["xi"]) for row in rows})
    mu_values = sorted({float(row["mu_MeV"]) for row in rows})
    converged_count = sum(1 for row in rows if str(row["converged"]).lower() == "true")

    if args.expect_mu0_only and any(abs(value) > 1e-9 for value in mu_values):
        fail("expected mu0-only artifact, but found non-zero mu_MeV values")

    meta_xi = meta.get("xi_coverage", {})
    meta_mu = meta.get("mu_q_coverage", {})
    if meta_xi.get("count") != len(xi_values):
        fail("meta xi_coverage.count does not match csv")
    if meta_mu.get("count") != len(mu_values):
        fail("meta mu_q_coverage.count does not match csv")

    report = {
        "tag": args.tag,
        "reference_root": normalize_relpath(reference_root, repo_root),
        "crossover_only": args.expect_crossover_only,
        "mu0_only": args.expect_mu0_only,
        "git_commit": manifest_generator.get("git_commit"),
        "generated_at_utc": manifest_generator.get("generated_at"),
        "crossover_rows": len(rows),
        "converged_rows": converged_count,
        "xi_values": xi_values,
        "mu_values_MeV": mu_values,
        "files": {
            "crossover_csv": normalize_relpath(crossover_csv, repo_root),
            "crossover_meta": normalize_relpath(crossover_meta, repo_root),
            "manifest": normalize_relpath(manifest_path, repo_root),
        },
    }

    if args.report_path:
        report_path = Path(args.report_path).resolve()
        report_path.parent.mkdir(parents=True, exist_ok=True)
        with report_path.open("w", encoding="utf-8") as fh:
            json.dump(report, fh, ensure_ascii=False, indent=2)

    print(json.dumps(report, ensure_ascii=False))


if __name__ == "__main__":
    main()
