#!/usr/bin/env python3

import argparse
import csv
import json
import math
from pathlib import Path


def parse_args():
    parser = argparse.ArgumentParser(
        description="Validate dense reference artifacts generated by build_dense_phase_reference.jl"
    )
    parser.add_argument("--reference-root", required=True, help="Directory containing generated reference artifacts")
    parser.add_argument("--tag", required=True, help="Artifact tag suffix")
    parser.add_argument("--min-crossover-rows", type=int, default=1, help="Minimum expected data rows in crossover csv")
    parser.add_argument("--expect-crossover-only", action="store_true", help="Assert that only crossover artifacts are present")
    parser.add_argument("--expect-full-reference", action="store_true", help="Assert that boundary, CEP, spinodal, and crossover artifacts are present")
    parser.add_argument("--expect-mu0-only", action="store_true", help="Assert that all mu_MeV values are zero")
    parser.add_argument("--report-path", help="Optional JSON report output path")
    return parser.parse_args()


def fail(message: str):
    raise SystemExit(f"[dense-reference-validate] {message}")


def load_json(path: Path):
    with path.open("r", encoding="utf-8") as fh:
        return json.load(fh)


def load_csv_rows(path: Path):
    with path.open("r", encoding="utf-8", newline="") as fh:
        reader = csv.DictReader(fh)
        fieldnames = reader.fieldnames or []
        if not fieldnames:
            fail(f"missing CSV header: {path}")
        rows = []
        for row in reader:
            extra = row.get(None) or []
            missing = [name for name in fieldnames if row.get(name) is None]
            if extra or missing:
                actual_count = len(fieldnames) + len(extra) - len(missing)
                fail(
                    f"malformed CSV row in {path} ending at physical line {reader.line_num}: "
                    f"expected {len(fieldnames)} fields, parsed {actual_count}; "
                    f"missing={missing}, extra_values={extra}"
                )
            rows.append(dict(row))
    return fieldnames, rows


def require_columns(fieldnames, required, artifact_name: str):
    missing = [name for name in required if name not in fieldnames]
    if missing:
        fail(f"{artifact_name} missing required columns: {missing}; found {fieldnames}")


def validate_cep_rows(fieldnames, rows, path: Path):
    modern_columns = {
        "result_status",
        "T_last_first_order_MeV",
        "muq_last_first_order_MeV",
        "muB_last_first_order_MeV",
        "T_first_monotone_MeV",
        "ambiguity_width_T_MeV",
        "temperature_resolution_target_MeV",
    }
    present_modern = modern_columns.intersection(fieldnames)
    if not present_modern:
        # The eight-column historical contract remains readable.
        return
    if present_modern != modern_columns:
        fail(
            f"partial modern CEP schema at {path}: present={sorted(present_modern)}, "
            f"required={sorted(modern_columns)}"
        )
    allowed = {"resolved", "ambiguous", "not_found"}
    def finite_value(value: str, label: str, index: int, *, positive: bool = False) -> float | None:
        text = value.strip()
        if not text:
            return None
        try:
            parsed = float(text)
        except ValueError:
            fail(f"non-numeric CEP {label} at {path}:{index}: {value!r}")
        if not math.isfinite(parsed):
            fail(f"non-finite CEP {label} at {path}:{index}: {value!r}")
        if positive and parsed <= 0:
            fail(f"non-positive CEP {label} at {path}:{index}: {value!r}")
        return parsed

    seen_xi: set[float] = set()
    for index, row in enumerate(rows, start=2):
        xi_text = row.get("xi", "").strip()
        try:
            xi_value = float(xi_text)
        except ValueError:
            fail(f"non-numeric CEP xi at {path}:{index}: {xi_text!r}")
        if not math.isfinite(xi_value):
            fail(f"non-finite CEP xi at {path}:{index}: {xi_text!r}")
        if xi_value in seen_xi:
            fail(f"duplicate CEP xi row at {path}:{index}: {xi_value}")
        seen_xi.add(xi_value)
        status = row.get("result_status", "").strip()
        if status not in allowed:
            fail(f"invalid CEP result_status at {path}:{index}: {status!r}")
        if status != "resolved" and (row.get("T_CEP_MeV", "").strip() or row.get("muq_CEP_MeV", "").strip()):
            fail(f"non-resolved CEP row publishes a single point at {path}:{index}")
        if status == "resolved" and not (
            row.get("T_CEP_MeV", "").strip() and row.get("muq_CEP_MeV", "").strip()
        ):
            fail(f"resolved CEP row lacks a finite single point at {path}:{index}")
        finite_value(row.get("T_CEP_MeV", ""), "T_CEP_MeV", index)
        finite_value(row.get("muq_CEP_MeV", ""), "muq_CEP_MeV", index)
        finite_value(
            row.get("temperature_resolution_target_MeV", ""),
            "temperature_resolution_target_MeV",
            index,
            positive=True,
        )
        if status == "ambiguous":
            low = row.get("T_last_first_order_MeV", "").strip()
            high = row.get("T_first_monotone_MeV", "").strip()
            if not low and not high:
                fail(f"ambiguous CEP row lacks phase evidence at {path}:{index}")
            low_value = finite_value(low, "T_last_first_order_MeV", index)
            high_value = finite_value(high, "T_first_monotone_MeV", index)
            if low_value is not None and high_value is not None and high_value < low_value:
                fail(f"ambiguous CEP evidence interval is reversed at {path}:{index}")
            width = finite_value(row.get("ambiguity_width_T_MeV", ""), "ambiguity_width_T_MeV", index)
            if width is not None and width < 0:
                fail(f"ambiguous CEP ambiguity width is negative at {path}:{index}")


def validate_manifest_artifact(artifacts, artifact_name: str, csv_path: Path, row_count: int, repo_root: Path):
    info = artifacts.get(artifact_name, {})
    if not info:
        fail(f"manifest missing artifacts.{artifact_name}")
    if info.get("row_count") != row_count:
        fail(f"manifest artifacts.{artifact_name}.row_count does not match csv row count")
    expected_relpath = normalize_relpath(csv_path, repo_root)
    if info.get("path") != expected_relpath:
        fail(f"manifest artifacts.{artifact_name}.path mismatch: expected {expected_relpath}, got {info.get('path')}")


def normalize_relpath(path: Path, root: Path) -> str:
    try:
        return path.relative_to(root).as_posix()
    except ValueError:
        return path.as_posix()


def main():
    args = parse_args()
    repo_root = Path(__file__).resolve().parents[2]
    reference_root = Path(args.reference_root).resolve()

    crossover_csv = reference_root / f"crossover_{args.tag}.csv"
    crossover_meta = reference_root / f"crossover_{args.tag}.meta.json"
    manifest_path = reference_root / f"phase_reference_{args.tag}_manifest.json"
    boundary_csv = reference_root / f"boundary_{args.tag}.csv"
    cep_csv = reference_root / f"cep_{args.tag}.csv"
    spinodal_csv = reference_root / f"spinodals_{args.tag}.csv"
    grid_convergence_csv = reference_root / f"phase_grid_convergence_{args.tag}.csv"

    required_paths = [crossover_csv, crossover_meta, grid_convergence_csv, manifest_path]
    if args.expect_full_reference:
        required_paths.extend([boundary_csv, cep_csv, spinodal_csv])
    for path in required_paths:
        if not path.is_file():
            fail(f"missing required artifact: {path}")

    fieldnames, rows = load_csv_rows(crossover_csv)
    if len(rows) < args.min_crossover_rows:
        fail(f"crossover row count {len(rows)} < required minimum {args.min_crossover_rows}")

    required_crossover_columns = [
        "xi",
        "mu_MeV",
        "T_crossover_MeV",
        "rho",
        "method",
        "converged",
        "derivative",
        "variable",
    ]
    require_columns(fieldnames, required_crossover_columns, "crossover")

    meta = load_json(crossover_meta)
    manifest = load_json(manifest_path)

    artifact_info = meta.get("artifact", {})
    if artifact_info.get("row_count") != len(rows):
        fail("meta artifact.row_count does not match crossover csv row count")

    meta_relpath = artifact_info.get("path")
    expected_meta_relpath = normalize_relpath(crossover_csv, repo_root)
    if meta_relpath != expected_meta_relpath:
        fail(f"meta artifact.path mismatch: expected {expected_meta_relpath}, got {meta_relpath}")

    manifest_generator = manifest.get("generator", {})
    meta_generator = meta.get("generator", {})
    if manifest_generator.get("git_commit") != meta_generator.get("git_commit"):
        fail("manifest generator.git_commit does not match meta generator.git_commit")

    provenance = manifest.get("provenance")
    if provenance is not None:
        if provenance.get("calculation_git_commit") != manifest_generator.get("git_commit"):
            fail("manifest provenance.calculation_git_commit does not match generator.git_commit")
        if not provenance.get("postprocess_git_commit"):
            fail("manifest provenance.postprocess_git_commit is missing")
        if meta.get("provenance") != provenance:
            fail("manifest provenance does not match crossover metadata provenance")

    if manifest_generator.get("crossover_only") != args.expect_crossover_only:
        fail("manifest crossover_only flag does not match workflow expectation")
    if manifest_generator.get("crossover_mu0_only") != args.expect_mu0_only:
        fail("manifest crossover_mu0_only flag does not match workflow expectation")

    artifacts = manifest.get("artifacts", {})
    validate_manifest_artifact(artifacts, "crossover", crossover_csv, len(rows), repo_root)
    grid_fields, grid_rows = load_csv_rows(grid_convergence_csv)
    require_columns(
        grid_fields,
        [
            "axis",
            "xi",
            "T_MeV",
            "level",
            "left",
            "right",
            "midpoint",
            "position_error_MeV",
            "density_error",
            "maxwell_area",
            "response_rtol",
            "converged",
            "reason",
        ],
        "grid_convergence",
    )
    validate_manifest_artifact(
        artifacts,
        "grid_convergence",
        grid_convergence_csv,
        len(grid_rows),
        repo_root,
    )

    if args.expect_crossover_only:
        unexpected = [name for name in ("boundary", "cep", "spinodals") if name in artifacts]
        if unexpected:
            fail(f"unexpected non-crossover artifacts present: {unexpected}")

    full_artifact_reports = {}
    if args.expect_full_reference:
        if args.expect_crossover_only:
            fail("--expect-full-reference conflicts with --expect-crossover-only")
        expected_non_crossover = {
            "boundary": (
                boundary_csv,
                ["xi", "T_MeV", "mu_transition_MeV", "rho_hadron", "rho_quark"],
            ),
            "cep": (
                cep_csv,
                [
                    "xi",
                    "T_CEP_MeV",
                    "muq_CEP_MeV",
                    "muB_CEP_MeV",
                    "uncertainty_T_MeV",
                    "T_bracket_low_MeV",
                    "T_bracket_high_MeV",
                    "bracket_width_T_MeV",
                ],
            ),
            "spinodals": (
                spinodal_csv,
                ["xi", "T_MeV", "mu_spinodal_hadron_MeV", "mu_spinodal_quark_MeV", "rho_spinodal_hadron", "rho_spinodal_quark"],
            ),
        }
        for artifact_name, (csv_path, required_columns) in expected_non_crossover.items():
            artifact_fields, artifact_rows = load_csv_rows(csv_path)
            require_columns(artifact_fields, required_columns, artifact_name)
            if artifact_name == "cep":
                validate_cep_rows(artifact_fields, artifact_rows, csv_path)
            validate_manifest_artifact(artifacts, artifact_name, csv_path, len(artifact_rows), repo_root)
            full_artifact_reports[artifact_name] = {
                "rows": len(artifact_rows),
                "xi_values": sorted({float(row["xi"]) for row in artifact_rows}) if artifact_rows else [],
                "columns": artifact_fields,
            }

    xi_values = sorted({float(row["xi"]) for row in rows})
    mu_values = sorted({float(row["mu_MeV"]) for row in rows})
    converged_count = sum(1 for row in rows if str(row["converged"]).lower() == "true")

    if args.expect_mu0_only and any(abs(value) > 1e-9 for value in mu_values):
        fail("expected mu0-only artifact, but found non-zero mu_MeV values")

    meta_xi = meta.get("xi_coverage", {})
    meta_mu = meta.get("mu_q_coverage", {})
    if meta_xi.get("count") != len(xi_values):
        fail("meta xi_coverage.count does not match csv")
    if meta_mu.get("count") != len(mu_values):
        fail("meta mu_q_coverage.count does not match csv")

    report = {
        "tag": args.tag,
        "reference_root": normalize_relpath(reference_root, repo_root),
        "crossover_only": args.expect_crossover_only,
        "mu0_only": args.expect_mu0_only,
        "git_commit": manifest_generator.get("git_commit"),
        "calculation_git_commit": (
            provenance.get("calculation_git_commit") if provenance else manifest_generator.get("git_commit")
        ),
        "postprocess_git_commit": (
            provenance.get("postprocess_git_commit") if provenance else manifest_generator.get("git_commit")
        ),
        "source_workflow_run_id": provenance.get("source_workflow_run_id") if provenance else None,
        "generated_at_utc": manifest_generator.get("generated_at"),
        "crossover_rows": len(rows),
        "converged_rows": converged_count,
        "grid_convergence_rows": len(grid_rows),
        "grid_unconverged_rows": sum(
            1 for row in grid_rows if str(row["converged"]).lower() != "true"
        ),
        "xi_values": xi_values,
        "mu_values_MeV": mu_values,
        "files": {
            "crossover_csv": normalize_relpath(crossover_csv, repo_root),
            "crossover_meta": normalize_relpath(crossover_meta, repo_root),
            "grid_convergence_csv": normalize_relpath(grid_convergence_csv, repo_root),
            "manifest": normalize_relpath(manifest_path, repo_root),
        },
        "full_reference_artifacts": full_artifact_reports,
    }

    if args.expect_full_reference:
        report["files"].update({
            "boundary_csv": normalize_relpath(boundary_csv, repo_root),
            "cep_csv": normalize_relpath(cep_csv, repo_root),
            "spinodal_csv": normalize_relpath(spinodal_csv, repo_root),
        })

    if args.report_path:
        report_path = Path(args.report_path).resolve()
        report_path.parent.mkdir(parents=True, exist_ok=True)
        with report_path.open("w", encoding="utf-8") as fh:
            json.dump(report, fh, ensure_ascii=False, indent=2)

    print(json.dumps(report, ensure_ascii=False))


if __name__ == "__main__":
    main()
