include(joinpath(@__DIR__, "runtime", "GapSolver.jl"))
include(joinpath(@__DIR__, "compat", "ImplicitGapLegacy.jl"))
include(joinpath(@__DIR__, "runtime", "ConstraintSolver.jl"))
include(joinpath(@__DIR__, "ImplicitProblem.jl"))
include(joinpath(@__DIR__, "compat", "ImplicitAdapters.jl"))
include(joinpath(@__DIR__, "spec", "ConstraintModes.jl"))
include(joinpath(@__DIR__, "spec", "ConstraintComponents.jl"))
include(joinpath(@__DIR__, "compat", "SchemaAdapter.jl"))
include(joinpath(@__DIR__, "orchestrator", "PrimaryStrategy.jl"))
include(joinpath(@__DIR__, "spec", "ProblemSpec.jl"))
include(joinpath(@__DIR__, "diagnostics", "SolverDiagnostics.jl"))
include(joinpath(@__DIR__, "diagnostics", "SolverDiagnosticsTypes.jl"))
include(joinpath(@__DIR__, "config", "SolverRuntimeConfig.jl"))
include(joinpath(@__DIR__, "orchestrator", "ProblemSpecOrchestrator.jl"))
include(joinpath(@__DIR__, "config", "StateSchema.jl"))
include(joinpath(@__DIR__, "governance", "CandidateGovernance.jl"))
include(joinpath(@__DIR__, "orchestrator", "SeedStrategies.jl"))
include(joinpath(@__DIR__, "spec", "Conditions.jl"))
include(joinpath(@__DIR__, "runtime", "GenericRootEngine.jl"))
include(joinpath(@__DIR__, "governance", "WeightedFallback.jl"))
include(joinpath(@__DIR__, "api", "SolverAPI.jl"))
include(joinpath(@__DIR__, "path", "PathContinuation.jl"))
include(joinpath(@__DIR__, "diff", "ThermoDiffContext.jl"))
include(joinpath(@__DIR__, "diff", "Targets.jl"))
include(joinpath(@__DIR__, "diff", "JacobianEngine.jl"))
include(joinpath(@__DIR__, "diff", "PilotAdapters.jl"))
include(joinpath(@__DIR__, "..", "derivatives", "DiffService.jl"))
